#服务的基础配置
#请求的根路径前缀。所有的请求都以/ai开头，例如AssistantController中的请求就是localhost:8080/ai/chat/completions
spring:
  webflux:
    base-path: /ai
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/assistant}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: ${LOGGING_LEVEL:info}


#业务相关的配置
#组织码
business:
  #大模型相关
  llm:
    #大模型的系列
    model-series: ${LLM_MODEL_SERIES:qwen}
    #模型调用的key
    api-key: ${LLM_API_KEY}
    #模型的地址
    url: ${LLM_ADDRESS}
    #具体模型的名字
    model: ${LLM_MODEL}




